---
api:
  restart: always
  build: .
  links:
    - db
  environment:
    - DATABASE_URI=postgres://base_api:pwgen_-sny_40@db:5432/postgres
  command: /usr/src/app/venv/bin/gunicorn -w 2 -b :8000 run:app
  ports:
    - 8000:8000
db:
  restart: always
  image: postgres
  volumes:
    - db:/docker-entrypoint-initdb.d
  ports:
    - 5432:5432
